# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: run-unit-tests
        name: Run unit tests
        entry: python -m unittest discover -s tests -p "test_*.py"
        language: system
        types: [python]
        pass_filenames: false
        always_run: true