services:
  jta:
    image: jta-prod:1.0.0
    build:
      context: .
      target: production
    container_name: jta-prod
    restart: unless-stopped
    env_file:
      - .env.prod
    ports:
      # Maps port 8080 in the container to port 8080 on the host machine
      - "8080:8080"
    environment:
      - RUNNING_IN_CONTAINER=true
    volumes:
      # Persists logs in a named volume for production
      - jta-logs:/app/logs
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    container_name: jta-redis-prod
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  jta-logs:
  redis-data:
