services:
  jta:
    image: jta-app:prod
    build:
      context: .
      target: production
    container_name: jta-prod
    restart: unless-stopped
    env_file:
      - .env.prod
    ports:
      # Maps port 80 in the container to port 8080 on the host machine
      - "8080:80"
    environment:
      - RUNNING_IN_CONTAINER=true
    volumes:
      # Persists logs in a named volume for production
      - jta-logs:/app/logs

volumes:
  jta-logs:
