services:
  jta:
    image: jta-app:prod
    container_name: jta-prod
    restart: unless-stopped
    env_file:
      - .env.prod
    ports:
      - "8080:8080"
    environment:
      - RUNNING_IN_CONTAINER=true
    volumes:
      - jta-logs:/app/logs
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: jta-redis-prod
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  jta-logs:
  redis-data:
