services:
  jta:
    # Overrides the build target to use the 'development' stage from your Dockerfile
    build:
      target: development
    image: jta-dev:1.0.0
    container_name: jta-dev
    # Uses development-specific environment variables
    env_file:
      - .env.dev
    # Overrides the port for the development server (which runs on 8000 with --reload)
    ports:
      - "8000:8000"
    volumes:
      # Mounts your local source code into the container for live-reloading
      - ./src:/app/src
      # Mounts a local logs directory
      - ./logs:/app/logs
    # Waits for the redis service to report a 'healthy' status before starting
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      # Check service health and API readiness
      test: ["CMD", "curl", "--fail", "http://localhost:8000/ready"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 15s
  redis:
    container_name: jta-redis-dev
    # The healthcheck ensures the jta-dev container won't start until Redis is ready
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
