services:
  jta:
    image: jta-app:prod
    container_name: jta-prod
    restart: unless-stopped
    env_file:
      - .env.prod
    ports:
      - "8080:8080"
    environment:
      - RUNNING_IN_CONTAINER=true
    volumes:
      - jta-logs:/app/logs

volumes:
  jta-logs:
