services:
  jta:
    image: jta-dev:1.0.0
    build:
      # Overrides the build target to use the development stage
      target: development
    container_name: jta-dev
    env_file:
      # Overrides the env_file to use your development secrets
      - .env.dev
    ports:
      # Overrides the ports for the development server
      - "8000:8000"
    environment:
      - RUNNING_IN_CONTAINER=true
    volumes:
      # Mounts your local source code for live-reloading
      # Also mounts a local log directory
      - ./src:/app/src
      - ./logs:/app/logs
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: jta-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
