version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Mount logs, input, and output directories separately
      - ./logs:/app/logs
      - ./input:/app/input
      - ./output:/app/output
