[tool.poetry]
name = "confluence-jira-task-sync"
version = "0.1.0"
description = "A tool to automate Jira and Confluence synchronization."
authors = ["Nguyen Tuan Dat <tdnguyen@vn.pepperl-fuchs.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
# Core application dependencies
atlassian-python-api = "^3.41.6"
pydantic = "^2.5.3"
punq = "^0.7.0"
requests = "^2.31.0"
python-dotenv = "^1.0.1"
pandas = "^2.2.0"
fastapi = "^0.111.0"
httpx = "^0.27.0"
uvicorn = {extras = ["standard"], version = "^0.29.0"}
python-multipart = "^0.0.9"

[tool.poetry.group.dev.dependencies]
# Tools for testing, formatting, and linting
pytest = "^7.4.4"
pytest-mock = "^3.12.0"
black = "^24.2.0"
ruff = "^0.2.2"
pre-commit = "^3.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
